apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: {{ template "config-server.fullname" . }}
labels:
    app: {{ template "config-server.name" . }}
    chart: {{ template "config-server.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ template "config-server.name" . }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ template "config-server.name" . }}
        release: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "mszarlinski/spring-petclinic-config-server"
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /health
              port: http
          readinessProbe:
            httpGet:
              path: /health
              port: http
          volumeMounts:
            - name: bootstrap-volume
              mountPath: /bootstrap.yml
              subPath: bootstrap.yml
            - name: configs-volume
              mountPath: /config
          resources:
{{ toYaml .Values.resources | indent 12 }}
      volumes:
        - name: bootstrap-volume
          configMap:
            name: {{ template "discovery-server.fullname" . }}-bootstrap
        - name: configs-volume
          configMap:
            name: {{ template "discovery-server.fullname" . }}-configs

