apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "discovery-server.fullname" . }}
  labels:
    app: {{ template "discovery-server.name" . }}
    chart: {{ template "discovery-server.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  bootstrap.yml: |-
    spring:
      profiles: docker
      cloud:
        config:
          uri: {{ template "config-server.url" . }}
      application:
        name: discovery-server

