apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "discovery-server.fullname" . }}
  labels:
    app: {{ template "discovery-server.name" . }}
    chart: {{ template "discovery-server.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  bootstrap.yml: |-
    spring:
      cloud:
        config:
          uri: http://{{ .Release.Name }}-config-server.petclinic.svc.cluster.local
      application:
        name: discovery-server
    ---
    spring:
      profiles: docker
      cloud:
        config:
          uri: http://{{ .Release.Name }}-config-server.petclinic.svc.cluster.local


        

